### ISSUE TITLE
Clicking to disable FirePHP4Chrome does not work

### ISSUE THREAD

**Issue by StokedIndustries** [aaronsaray/FirePHP4Chrome#22]
Even if the icon is greyed out, indicating it should be disabled, I still get FirePHP output in my console. I have tried clicking to enable it, then clicking again to disable it, and I still get output in my console.

I am running Chrome 39 on OS X Yosemite.

**Comment by aaronsaray** [comment]
Oh man - sorry about that!  I'll take a look in a few days... Thanks for reporting it!

**Comment by StokedIndustries** [comment]
Thanks! I updated to Chrome 40 but the issue still persists, if that helps you track down the bug.

**Comment by aaronsaray** [comment]
I am using the most recent chrome and the most recent version of the plugin.  When I load it (with the icon in full color) and go to example.com, I get the following headers sent:

```
GET / HTTP/1.1
Host: example.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36 FirePHP/4Chrome
DNT: 1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
X-FirePHP-Version: 0.0.6
X-Wf-Max-Combined-Size: 261120
```

As you can see, it is sending the two firephp/wildfire headers in this request.

Then, I disabled the extension by clicking the icon (and it turned grey).  And got the following headers:

```
GET / HTTP/1.1
Host: example.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
DNT: 1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

It is not sending the header.

When you see the info still appears in the console, is it even after a reload?  Or did you mean you expect it to disappear when you click the button immediately?  Because, when you click the button, that means it is disabled for FUTURE requests.

Let me know if I'm misunderstanding your comment - or if I have it right.  Thanks!

**Comment by StokedIndustries** [comment]
If I click to disable it, then reload, the info still comes into the console. Even after multiple reloads, closing the tab/window, opening new one and trying again, it's still there.

**Comment by aaronsaray** [comment]
Hrm - that is weird... I haven't yet been able to duplicate this.

Can you send me the request headers from your browser?  You should be able to do this by clicking on the network tab, clicking on your first request, and clicking 'view source' on the request headers?  Paste that for me?  Thanks so much!

**Comment by StokedIndustries** [comment]
Request headers from a test with FirePHP4Chrome disabled, with Cookie headers removed. Let me know if you need the cookie headers, I'll have to clean it up before posting.

It looks like FirePHP headers aren't present, but they come into the console somehow anyway. Yes FirePHP output came back with the response to this request.

GET /redacted/ HTTP/1.1
Host: redacted
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
DNT: 1
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

**Comment by aaronsaray** [comment]
What exact tool and version are you using to generate the FirePHP (wildfire) responses?  Perhaps there is a bug in there that is sending the responses regardless of if the chrome extension sends a request for them.  Can you link me to the source code?

**Comment by analogrithems** [comment]
@StokedIndustries is right, I get the same issue.  Here's some more feedback.  As you can see from the screen shot it's disabled.  Yet, console still says it's active.  To clarify what @StokedIndustries was trying to say, the server will always send the messages regardless of browser settings.  But when disabled the browser should not show the messages in the console.  You can test this on the following URL: https://staging.activityrez.com/ar-core/
![screen shot 2015-03-04 at 12 45 32 pm](https://cloud.githubusercontent.com/assets/103706/6495299/d72515ce-c26c-11e4-9cde-967b74461240.PNG)
![screen shot 2015-03-04 at 12 46 01 pm](https://cloud.githubusercontent.com/assets/103706/6495300/d7262ba8-c26c-11e4-986b-7e6b92d7500b.PNG)

**Comment by aaronsaray** [comment]
Ah -thanks for all the details!

So - the message that appears in the console is generated from the plugin reminding you to do a refresh if you want content.  It doesn't actually process any content.  This is supposed to be a helpful reminder for people who open the console and don't see their debug information.

When the plugin is disabled, it actually isn't processing anything - so you can ignore this message.

I did want to remove it for you - however, there is a bug in chrome.  See: <https://code.google.com/p/chromium/issues/detail?id=405096> - it basically doesn't allow the devtools plugin to get the settings.  So when this is fixed, I will definitely apply this.  

Sorry for the confusion!

**Comment by analogrithems** [comment]
Actually if you notice in the screen shot above the first message after firephp logging activated is a firephp log, notice the object backtrace

**Comment by aaronsaray** [comment]
Oh you're right - sorry - I missed that.

Weird - when I tested it out on that site, I did not see such a message.  Hrm.  Is the debugging still enabled on that test server?  can you send a non-business-related trace?

**Comment by aaronsaray** [comment]
Any update on this?

**Comment by digitalmediums** [comment]
Sorry, yes you can still verify with this
goto https://staging.activityrez.com/ar-core/ put in any bad username and password with the firephp disabled and you'll still see messages in the console.  Also I noticed it only happens when you load the page with the console not having focus.
https://staging.activityrez.com/ar-core/api/login?username=asdfasd&password=sdfasdf&email=&company=&is_signup=false&token=NEW

Creating a video, will link it in just a bit

**Comment by digitalmediums** [comment]
https://dl.dropboxusercontent.com/u/13113270/firephp/eh5v.files/html5video/firephp_issue.m4v

**Comment by aaronsaray** [comment]
Thanks so much for your help :)  I've fixed this now.

What you should know: your server is sending wildfire headers even when the extension wasn't requesting them. This seems like a configuration issue or a bug with your firePHP library.  It should only send them when they're in the request.
