### ISSUE TITLE
auto-expand groups

### ISSUE THREAD

**Issue by cweiske** [aaronsaray/FirePHP4Chrome#24]
Groups are displayed as closed, which means I have to manually open them to see the content.

It would be helpful if the groups would be open automatically (or have an option to configure that).

![Screenshot](http://fotos.cweiske.de/screenshots/2015-06-02%20firephp4chrome%20groups%20closed.png)

**Comment by aaronsaray** [comment]
Can you tell me if this is happening on all group sends?  By default, the wildfire response can issue two types of group requests - group and group collapsed.  What you're demonstrating looks like your debug tool is sending the group collapsed header - not just the group header.  

Is it possible to try sending just the group command without sending the collapsed property?  Or, I guess I'm trying to figure out if this is a bug - or if you're asking for a feature to make it easier to use if the debug library you're using doesn't auto expand groups on purpose.

thanks!

**Comment by cweiske** [comment]
You are right. My lib is sending collapsed headers. Sorry.
